project:
  type: website
  output-dir: _site

editor:
  render-on-save: true

bibliography: references.bib
csl: elsevier-vancouver.csl


filters:
  - tooltips
  
website:
  title: ""
  description: "A framework for extracting and analyzing causal attributions"
  favicon: favicon_tight.png
  search: 
    location: navbar
    # type: overlay
  sidebar:
      - id: "extraction"
        title: "Extraction"
        contents: 
          - section: "Extraction"
            contents:
              - extraction/extraction.qmd
              - extraction/annotation.qmd
              - extraction/c-bert.qmd
              
      - id: "processing"
        title: "Processing"
        contents:
          - section: "Processing"
            contents:
              - processing/processing.qmd
              - processing/tuple-construction.qmd
              - processing/aggregation.qmd
  navbar:
    logo: favicon_tight.png
    left:
      - text: "Home"
        file: index.qmd
      # - text: "Framework"
      #   file: framework/framework.qmd
      - text: "Extraction"
        menu:
          - text: "Overview"
            file: extraction/extraction.qmd
          - text: "Annotation"
            file: extraction/annotation.qmd
          - text: "C-BERT"
            file: extraction/c-bert.qmd
      - text: "Processing"
        menu:
          - text: "Overview"
            file: processing/processing.qmd
          - text: "Tuple Construction"
            file: processing/tuple-construction.qmd
          - text: "Aggregation"
            file: processing/aggregation.qmd
      # - text: "ACG"
      #   file: acg/acg.qmd
      - text: "Resources"
        file: resources.qmd
    right:
      - icon: github
        href: https://github.com/padjohn/causalsemantics
        aria-label: GitHub
  page-footer:
    left: "Causal Semantics"
    right: 
      - text: "License: CC BY 4.0"

format:
  html:
    theme: 
      - darkly
      - styles.scss
    toc: true
    toc-depth: 3
    code-fold: true
    code-tools: true
    html-math-method: katex
    highlight-style: github
    mermaid:
      theme: dark
      # themeVariables:
        # primaryColor: '#BB2528'
        # primaryTextColor: '#fff'
        # primaryBorderColor: '#7C0000'
        # lineColor: '#F8B229'
        # secondaryColor: '#006100'
        # tertiaryColor: '#fff'
    
execute:
  freeze: auto
  cache: true